# frozen_string_literal: true

#####################################
# 'brew tap'

# Provides the brew bundle command
tap 'homebrew/bundle'
# Contains Casks for installing various device drivers.
tap 'homebrew/cask-drivers'

#####################################
# 'brew install'

# libraries / utilities
brew 'ack' # Search tool like grep, but optimized for programmers
brew 'asdf' # Extendable version manager with support for Ruby, Node.js, Erlang & more
brew 'apfel' # A command-line tool to manage Apple Silicon's performance modes
# brew 'bash'
brew 'git' # Distributed revision control system
# brew 'git-extras' # Git utilities -- repo summary, repl, changelog population, author commit percentages and more
brew 'tree' # Display directories as trees (with optional color/HTML output)
brew 'wget' # Internet file retriever
brew 'bash-completion' # Programmable completion for Bash 3.2
# brew 'zsh-completions' # Additional completion definitions for zsh
# brew 'hub' # GitHub support to git
brew 'coreutils' # GNU File, Shell, and Text utilities
brew 'direnv' # Load/unload environment variables based on $PWD
# brew 'pkg-config' # Manage compile and link flags for libraries
# brew 'gpg' # GNU Privacy Guard
# brew 'gpg-agent' # GnuPG cryptographic agent
# brew 'gpg2' # GNU Privacy Guard
# brew 'autoconf' # Automatic configure script builder
# brew 'automake' # Tool for generating GNU Standards-compliant Makefiles
# brew 'gnupg' # GNU Privacy Guard
# brew 'gnupg2' # GNU Pretty Good Privacy (PGP) package
# brew 'openssl' # SSL/TLS cryptography library
brew 'jq' # Lightweight and flexible command-line JSON processor
brew 'libpq' # Postgres C API library
brew 'libyaml' # YAML Parser
brew 'mas' # Mac App Store command-line interface
brew 'pkg-config' # Package compiler and linker metadata toolkit
# brew 'libtool' # Generic library support script
# brew 'heroku'
# brew 'gh' # GitHub command-line tool
# brew 'go' # Open source programming language to build simple/reliable/efficient software

# data stores and tools
# brew 'mysql'
# brew 'mycli' # CLI for MySQL with auto-completion and syntax highlighting
# brew 'postgresql', restart_service: :changed
# brew 'postgresql@14', restart_service: :changed
# brew 'pgcli' # CLI for Postgres with auto-completion and syntax highlighting
# brew 'neo4j' # Robust (fully ACID) transactional property graph database
# brew 'redis', restart_service: :changed
# brew 'mongodb' # High-performance, schema-free, document-oriented database
# brew 'memcached'
# brew 'rabbitmq'
# brew 'kafka'
# brew 'rabbitmq' # Most widely deployed open source message broker.
# brew 'activemq' # Apache ActiveMQ: powerful open source messaging server
# brew 'presto'
# brew 'apache-drill'
# brew 'influxdb'
# brew 'zookeeper' # Centralized server for distributed coordination of services
# brew 'yarn'
# brew 'kubernetes-cli' # Kubernetes command-line interface
# brew 'memcached' # High performance, distributed memory object caching system
# brew 'elasticsearch' # Distributed search & analytics engine

# media libraries and tools
# brew 'ghostscript' # Interpreter for PostScript and PDF
# brew 'imagemagick' # Tools and libraries to manipulate images in many formats
# brew 'fdk-aac'
# brew "ffmpeg", args: ["build-from-source", "with-fdk-aac", "with-ffplay", "with-freetype", "with-libass", "with-libquvi", "with-libvorbis", "with-libvpx", "with-opus", "with-x265", "with-openh264"]
# brew "ffmpeg"
# brew 'media-info'
# brew 'youtube-dl'
# brew 'vips'
brew 'plantuml' # Draw UML diagrams

# aws tools
# brew 'terraform' # Tool to build, change, and version infrastructure
# brew 'awscli'
# brew 'chamber'
# brew 'tfenv'
# brew 's3cmd'
# brew 'awslogs'
# brew 'cli53'
# brew 'aws-elasticbeanstalk'
# brew 'aws-sam-cli'
# brew 'aws-shell'
# brew 'aws-okta'
# brew 'aws-vault'
# brew 'aws-iam-authenticator'
# brew 'aws-sso-util'
# brew 'amazon-ecs-cli' # CLI for Amazon ECS to manage clusters and tasks for development.

#####################################
# 'brew install --cask'

# set arguments for all 'brew install --cask' commands
cask_args appdir: '~/Applications', require_sha: true


# COMMUNICATIONS
cask 'discord' # Voice and text chat software
cask 'slack' # Team communication and collaboration software
# cask 'telegram' # Messaging app with a focus on speed and security
cask 'zoom' # Video communication and virtual meeting platform

# DEVELOPMENT
cask 'brave-browser' # Web browser focusing on privacy
# cask 'firefox'
# cask 'microsoft-edge'
cask 'bruno' # Open source IDE for exploring and testing APIs
cask 'cursor' # Write, edit, and chat about your code with AI
cask 'dbeaver-community' # Universal database tool and SQL client
cask 'docker-desktop' # App to build and share containerised applications and microservices
# cask 'jetbrains-toolbox' # JetBrains tools manager
# cask 'postman' # Collaboration platform for API development
# cask 'sourcetree' # Graphical client for Git version control
cask 'visual-studio-code' # Open-source code editor - Installs CLI tool `code`

# MEDIA
# cask 'gimp' # Free and open-source image editor
# cask 'inkscape' # Vector graphics editor
# cask 'vlc' # Multimedia player

# OPERATIONS
cask '1password' # Password manager that keeps all passwords secure behind one password
cask 'chatgpt' # OpenAI's official ChatGPT desktop app
cask 'notion' # App to write, plan, collaborate, and get organised

# SYSTEM
# cask 'caffeine' # Utility that prevents the system from going to sleep
cask 'displaylink' # Drivers for DisplayLink docks, adapters and monitors
cask 'elgato-stream-deck' # Assign keys, and then decorate and label them
cask 'google-drive' # Client for the Google Drive storage service
cask 'hiddenbar' # Utility to hide menu bar items
cask 'maccy' # Clipboard manager
cask 'stats' # System monitor for the menu bar
# Quicklook
cask 'qlcolorcode' # Quick Look plug-in that renders source code with syntax highlighting
cask 'qlvideo' # Thumbnails, static previews, cover art and metadata for video files

#####################################
# 'mas install'

# mas 'Window Tidy', id: 456609775
# mas 'Amphetamine', id: 937984704
